### ISSUE TITLE
Code generation in example (from this repo) not successfully generating .scala file

### ISSUE THREAD

**Issue by evbo** [apollographql/apollo-scalajs#18]
Hi, I downloaded this repo and after installing apollo tried running the example but got the below error that looks to be source code generation failing.

Perhaps is this due to a bug in a newer version of apollo than you might be using? What version of apollo do you test against?

I'm using:
```
apollo --version
apollo/2.1.9 linux-x64 node-v10.14.2

npm --version
6.4.1
```
Here's the error I get:
```
me@machine:/home/me/apollo-scalajs-master$ sbt example/fastOptJS::startWebpackDevServer
[info] Loading settings from idea.sbt,sbt-updates.sbt ...
[info] Loading global plugins from /nfs/u/me/.sbt/1.0/plugins
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /home/me/apollo-scalajs-master/project
[info] Updating ProjectRef(uri("file:/home/me/apollo-scalajs-master/project/"), "apollo-scalajs-master-build")...
[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn]  * org.scala-js:sbt-scalajs:0.6.24 is selected over 0.6.22
[warn]      +- ch.epfl.scala:sbt-scalajs-bundler:0.13.1 (scalaVersion=2.12, sbtVersion=1.0) (depends on 0.6.22)
[warn]      +- default:apollo-scalajs-master-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0) (depends on 0.6.22)
[warn] Run 'evicted' to see detailed eviction warnings
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
/home/me/apollo-scalajs-master/tests/build.sbt:18: warning: value RuntimeDOM in trait DependencyBuilders is deprecated (since 0.6.20): Requesting a DOM-enabled JS env with `jsDependencies += RuntimeDOM` or `requiresDOM := true` will not be supported in Scala.js 1.x. Instead, explicitly select a suitable JS with `jsEnv`, e.g., `jsEnv := new org.scalajs.jsenv.jsdomnodejs.JSDOMNodeJSEnv`.
jsDependencies += RuntimeDOM % Test
                  ^
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Set current project to apollo-scalajs (in build file:/home/me/apollo-scalajs-master/)
[info] Updating core...
[info] Done updating.
[info] Updating react...
[info] Done updating.
[info] Updating example...
[info] Done updating.
[info] Compiling 11 Scala sources to /home/me/apollo-scalajs-master/core/target/scala-2.12/classes ...
 ›   Error: Unexpected argument: 
 ›   /home/me/apollo-scalajs-master/example/t
 ›   arget/scala-2.12/src_managed/main/graphql.scala
 ›   See more help with --help
[info] Done compiling.
[info] Compiling 4 Scala sources to /home/me/apollo-scalajs-master/react/target/scala-2.12/classes ...
[info] /home/me/apollo-scalajs-master/react/src/main/scala/com/apollographql/scalajs/react/Mutation.scala:21:26: Using fallback derivation for type Error (derivation: MacroReadersImpl)
[info]       Reader.optionReader[Error].read(dyn.error.asInstanceOf[js.Object]),
[info]                          ^
[info] /home/me/apollo-scalajs-master/react/src/main/scala/com/apollographql/scalajs/react/Query.scala:16:36: Using fallback derivation for type Error (derivation: MacroReadersImpl)
[info]     val error = Reader.optionReader[Error].read(dyn.error.asInstanceOf[js.Object])
[info]                                    ^
[info] Done compiling.
[info] Compiling 5 Scala sources to /home/me/apollo-scalajs-master/example/target/scala-2.12/classes ...
[error] source file '/home/me/apollo-scalajs-master/example/target/scala-2.12/src_managed/main/graphql.scala' could not be found
[error] one error found
[error] (example / Compile / compileIncremental) Compilation failed
[error] Total time: 20 s, completed Jan 9, 2019 5:55:13 PM
```

**Comment by evbo** [comment]
tried installing an older version of apollo and still getting the same result as above. So could it be due to my version of node? Perhaps some other environment settings?

```
apollo --version
 ?   Warning: apollo update available from 2.1.0 to 2.1.9
apollo/2.1.0 linux-x64 node-v10.14.2
```

**Comment by evbo** [comment]
So I downloaded your older `2.0` release, and sure enough this problem I was experiencing from the latest master goes away, unfortunately there's other compilation errors (see below).

So then perhaps this is a compatibility issue with the latest `apollo` version(s)?

```
apollo-codegen --version
0.20.2

me@machine:/nfs/u/me/Downloads/apollo-scalajs-0.2.0$ sbt example/fastOptJS::startWebpackDevServer
[info] Loading project definition from /nfs/u/me/Downloads/apollo-scalajs-0.2.0/project
[info] Set current project to apollo-scalajs-0-2-0 (in build file:/nfs/u/me/Downloads/apollo-scalajs-0.2.0/)
[info] Updating {file:/nfs/u/me/Downloads/apollo-scalajs-0.2.0/}example...
[info] Resolving org.eclipse.jetty#jetty-continuation;8.1.16.v20140903 ...
[info] Done updating.
[info] Compiling 5 Scala sources to /nfs/u/me/Downloads/apollo-scalajs-0.2.0/example/target/scala-2.12/classes...
[error] <macro>:10: not found: value AuthorQuery
[error]     type Props = AuthorQuery.Props#WithExtra[AuthorView.ExtraProps]
[error]                  ^
[error] <macro>:7: value data is not a member of AuthorView.this.Props
[error]     def render(): ReactElement = props.data.map(d => div(d.author.toString)).getOrElse[TagComponent[Any]](h1("loading!"))
[error]                                        ^
[error] <macro>:14: value data is not a member of com.apollographql.scalajs.AuthorView.Props
[error]       def render(): ReactElement = props.data.map(d => div(d.author.toString)).getOrElse[TagComponent[Any]](h1("loading!"))
[error]                                          ^
[error] <macro>:17: not found: value AuthorQuery
[error]     val WithData = graphqlWithVariables(AuthorQuery) { (e: AuthorView.ExtraProps) => Some(AuthorQuery.Variables(e.id)) }(this)
[error]                                         ^
[error] <macro>:17: not found: value AuthorQuery
[error]     val WithData = graphqlWithVariables(AuthorQuery) { (e: AuthorView.ExtraProps) => Some(AuthorQuery.Variables(e.id)) }(this)
[error]                                                                                           ^
[error] <macro>:16: not found: value AllPostsQuery
[error]     val WithData = graphql(AllPostsQuery)(this)
[error]                            ^
[error] <macro>:10: not found: value AllPostsQuery
[error]     type Props = AllPostsQuery.Props
[error]                  ^
[error] <macro>:7: value data is not a member of PostsView.this.Props
[error]     def render(): ReactElement = props.data.map(d => div(d.posts.toList.flatten.flatten.map(post => div(key := post.id.toString)(h1(post.title.getOrElse[String]("???")), h2(post.votes.getOrElse(0).toString), UpVote.WithData(UpVote.ExtraProps(post.id, v => println(s"Upvote result: $v"))))))).getOrElse[TagComponent[Any]](h1("loading!"))
[error]                                        ^
[error] <macro>:14: value data is not a member of com.apollographql.scalajs.PostsView.Props
[error]       def render(): ReactElement = props.data.map(d => div(d.posts.toList.flatten.flatten.map(post => div(key := post.id.toString)(h1(post.title.getOrElse[String]("???")), h2(post.votes.getOrElse(0).toString), UpVote.WithData(UpVote.ExtraProps(post.id, v => println(s"Upvote result: $v"))))))).getOrElse[TagComponent[Any]](h1("loading!"))
[error]                                          ^
[error] <macro>:16: not found: value UpVoteMutation
[error]     type Props = UpVoteMutation.Props#WithExtra[UpVote.ExtraProps]
[error]                  ^
[error] <macro>:9: value mutate is not a member of UpVote.this.Props
[error]       props.mutate(UpVoteMutation.Variables(props.extraProps.postId)).foreach(r => {
[error]             ^
[error] <macro>:9: not found: value UpVoteMutation
[error]       props.mutate(UpVoteMutation.Variables(props.extraProps.postId)).foreach(r => {
[error]                    ^
[error] <macro>:9: value extraProps is not a member of UpVote.this.Props
[error]       props.mutate(UpVoteMutation.Variables(props.extraProps.postId)).foreach(r => {
[error]                                                   ^
[error] <macro>:11: value extraProps is not a member of UpVote.this.Props
[error]         props.extraProps.update(r)
[error]               ^
[error] <macro>:22: value mutate is not a member of com.apollographql.scalajs.UpVote.Props
[error]         props.mutate(UpVoteMutation.Variables(props.extraProps.postId)).foreach(r => {
[error]               ^
[error] <macro>:22: not found: value UpVoteMutation
[error]         props.mutate(UpVoteMutation.Variables(props.extraProps.postId)).foreach(r => {
[error]                      ^
[error] <macro>:22: value extraProps is not a member of com.apollographql.scalajs.UpVote.Props
[error]         props.mutate(UpVoteMutation.Variables(props.extraProps.postId)).foreach(r => {
[error]                                                     ^
[error] <macro>:24: value extraProps is not a member of com.apollographql.scalajs.UpVote.Props
[error]           props.extraProps.update(r)
[error]                 ^
[error] <macro>:28: not found: value UpVoteMutation
[error]     case class ExtraProps(postId: Int, update: UpVoteMutation.Data => Unit)
[error]                                                ^
[error] <macro>:28: not found: value UpVoteMutation
[error]     case class ExtraProps(postId: Int, update: UpVoteMutation.Data => Unit)
[error]                                                ^
[error] <macro>:29: not found: value UpVoteMutation
[error]     val WithData = graphql(UpVoteMutation)(this)
[error]                            ^
[error] <macro>:28: not found: value UpVoteMutation
[error]     case class ExtraProps(postId: Int, update: UpVoteMutation.Data => Unit)
[error]                                                ^
[error] /nfs/u/me/Downloads/apollo-scalajs-0.2.0/example/target/scala-2.12/src_managed/main/graphql.scala:7: type GraphQLQuery is not a member of package com.apollographql.scalajs.com.apollographql.scalajs
[error] object AuthorQuery extends com.apollographql.scalajs.GraphQLQuery {
[error]                                                      ^
[error] /nfs/u/me/Downloads/apollo-scalajs-0.2.0/example/target/scala-2.12/src_managed/main/graphql.scala:15: object gql is not a member of package com.apollographql.scalajs.com.apollographql.scalajs
[error]   val operation = com.apollographql.scalajs.gql(operationString)
[error]                                             ^
[error] /nfs/u/me/Downloads/apollo-scalajs-0.2.0/example/target/scala-2.12/src_managed/main/graphql.scala:36: type GraphQLQuery is not a member of package com.apollographql.scalajs.com.apollographql.scalajs
[error] object AllPostsQuery extends com.apollographql.scalajs.GraphQLQuery {
[error]                                                        ^
[error] /nfs/u/me/Downloads/apollo-scalajs-0.2.0/example/target/scala-2.12/src_managed/main/graphql.scala:45: object gql is not a member of package com.apollographql.scalajs.com.apollographql.scalajs
[error]   val operation = com.apollographql.scalajs.gql(operationString)
[error]                                             ^
[error] /nfs/u/me/Downloads/apollo-scalajs-0.2.0/example/target/scala-2.12/src_managed/main/graphql.scala:64: type GraphQLMutation is not a member of package com.apollographql.scalajs.com.apollographql.scalajs
[error] object UpVoteMutation extends com.apollographql.scalajs.GraphQLMutation {
[error]                                                         ^
[error] /nfs/u/me/Downloads/apollo-scalajs-0.2.0/example/target/scala-2.12/src_managed/main/graphql.scala:73: object gql is not a member of package com.apollographql.scalajs.com.apollographql.scalajs
[error]   val operation = com.apollographql.scalajs.gql(operationString)
[error]                                             ^
[error] 28 errors found
[error] (example/compile:compileIncremental) Compilation failed
[error] Total time: 7 s, completed Jan 10, 2019 12:46:17 PM

```

**Comment by evbo** [comment]
@shadaj So I think I've cornered the issue and am now successfully able to code generate your latest master version with the following task in `build.sbt`:

```
val namespace = "com.apollographql.scalajs"

(sourceGenerators in Compile) += Def.task {
  import scala.sys.process._

  val out = (sourceManaged in Compile).value

  out.mkdirs()

  val graphQLScala = out / "graphql.scala"

  Seq(
    "apollo",
    "codegen:generate",
    graphQLScala.getAbsolutePath,
    "--target=scala",
    s"--namespace=$namespace",
    s"--localSchemaFile=${(baseDirectory.value / "schema.json").getAbsolutePath}",
    s"--queries=${((sourceDirectory in Compile).value / "graphql").getAbsolutePath}/*.graphql"
  ).!

  Seq(graphQLScala)
}

watchSources ++= ((sourceDirectory in Compile).value / "graphql" ** "*.graphql").get
```

However, please note that due to other issues compilation is failing still:

```
[error] /nfs/u/me/Downloads/apollo-scalajs-master/example/src/main/scala/com/apollographql/scalajs/Main.scala:32:20: Cannot prove that Unit =:= com.apollographql.scalajs.PostsView.Props.
[error]           PostsView(),
[error]              
```

**Comment by evbo** [comment]
Thanks! In the meantime until #17 is merged are you familiar with what this error might be caused by?

```
[info] Fast optimizing /home/me/cars/target/scala-2.12/scalajs-bundler/main/memory-selection-client-fastopt.js
[error] Referring to non-existent class magnolia.Magnolia$
[error]   called from com.apollographql.scalajs.ApolloBoostClient$.apolloboostclientoptionsTypeclass$macro$9$1()slinky.readwrite.Writer
[error]   called from com.apollographql.scalajs.ApolloBoostClient$.apply(java.lang.String)com.apollographql.scalajs.ApolloBoostClient
[error]   called from org.tou.views.App.constructor
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   com.apollographql.scalajs.ApolloBoostClient$
[error]   org.tou.views.App
[error] Referring to non-existent class magnolia.Param
[error]   called from com.apollographql.scalajs.ApolloBoostClient$.apolloboostclientoptionsTypeclass$macro$9$1()slinky.readwrite.Writer
[error]   called from com.apollographql.scalajs.ApolloBoostClient$.apply(java.lang.String)com.apollographql.scalajs.ApolloBoostClient
[error]   called from org.tou.views.App.constructor
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   com.apollographql.scalajs.ApolloBoostClient$
[error]   org.tou.views.App
[error] Referring to non-existent method magnolia.Magnolia$.param(java.lang.String,java.lang.Object,scala.Function0,scala.Function1)magnolia.Param
[error]   called from com.apollographql.scalajs.ApolloBoostClient$.apolloboostclientoptionsTypeclass$macro$9$1()slinky.readwrite.Writer
[error]   called from com.apollographql.scalajs.ApolloBoostClient$.apply(java.lang.String)com.apollographql.scalajs.ApolloBoostClient
[error]   called from org.tou.views.App.constructor
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   com.apollographql.scalajs.ApolloBoostClient$
[error]   org.tou.views.App
[error] Referring to non-existent method magnolia.Magnolia$.caseClass(java.lang.String,scala.Boolean,scala.Boolean,[magnolia.Param,scala.Function1)magnolia.CaseClass
[error]   called from com.apollographql.scalajs.ApolloBoostClient$.apolloboostclientoptionsTypeclass$macro$9$1()slinky.readwrite.Writer
[error]   called from com.apollographql.scalajs.ApolloBoostClient$.apply(java.lang.String)com.apollographql.scalajs.ApolloBoostClient
[error]   called from org.tou.views.App.constructor
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   com.apollographql.scalajs.ApolloBoostClient$
[error]   org.tou.views.App
[error] Referring to non-existent method slinky.readwrite.Writer$.combine(magnolia.CaseClass)slinky.readwrite.Writer
[error]   called from com.apollographql.scalajs.ApolloBoostClient$.apolloboostclientoptionsTypeclass$macro$9$1()slinky.readwrite.Writer
[error]   called from com.apollographql.scalajs.ApolloBoostClient$.apply(java.lang.String)com.apollographql.scalajs.ApolloBoostClient
[error]   called from org.tou.views.App.constructor
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   com.apollographql.scalajs.ApolloBoostClient$
[error]   org.tou.views.App
[error] Referring to non-existent method magnolia.Magnolia$.param(java.lang.String,java.lang.Object,scala.Function0,scala.Function1)magnolia.Param
[error]   called from com.apollographql.scalajs.react.ApolloProvider$.propsTypeclass$macro$1$1()slinky.readwrite.Writer
[error]   called from com.apollographql.scalajs.react.ApolloProvider$.<init>()
[error]   called from org.tou.views.App.render(org.tou.views.App)slinky.core.facade.ReactElement
[error]   called from org.tou.views.App.render
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   com.apollographql.scalajs.react.ApolloProvider$
[error]   org.tou.views.App
[error] Referring to non-existent method magnolia.Magnolia$.caseClass(java.lang.String,scala.Boolean,scala.Boolean,[magnolia.Param,scala.Function1)magnolia.CaseClass
[error]   called from com.apollographql.scalajs.react.ApolloProvider$.propsTypeclass$macro$1$1()slinky.readwrite.Writer
[error]   called from com.apollographql.scalajs.react.ApolloProvider$.<init>()
[error]   called from org.tou.views.App.render(org.tou.views.App)slinky.core.facade.ReactElement
[error]   called from org.tou.views.App.render
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   com.apollographql.scalajs.react.ApolloProvider$
[error]   org.tou.views.App
[error] Referring to non-existent method slinky.readwrite.Writer$.combine(magnolia.CaseClass)slinky.readwrite.Writer
[error]   called from com.apollographql.scalajs.react.ApolloProvider$.propsTypeclass$macro$1$1()slinky.readwrite.Writer
[error]   called from com.apollographql.scalajs.react.ApolloProvider$.<init>()
[error]   called from org.tou.views.App.render(org.tou.views.App)slinky.core.facade.ReactElement
[error]   called from org.tou.views.App.render
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   com.apollographql.scalajs.react.ApolloProvider$
[error]   org.tou.views.App
[error] Referring to non-existent method slinky.readwrite.Writer$.combine(magnolia.CaseClass)slinky.readwrite.Writer
[error]   called from com.apollographql.scalajs.react.Query$.propsTypeclass$macro$56$1()slinky.readwrite.Writer
[error]   called from com.apollographql.scalajs.react.Query$.<init>()
[error]   called from org.tou.views.CarView.render(org.tou.views.CarView)slinky.core.facade.ReactElement
[error]   called from org.tou.views.CarView.render
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   com.apollographql.scalajs.react.Query$
[error]   org.tou.views.CarView
[error] Referring to non-existent method magnolia.Magnolia$.param(java.lang.String,java.lang.Object,scala.Function0,scala.Function1)magnolia.Param
[error]   called from com.apollographql.scalajs.react.Query$.propsTypeclass$macro$56$1()slinky.readwrite.Writer
[error]   called from com.apollographql.scalajs.react.Query$.<init>()
[error]   called from org.tou.views.CarView.render(org.tou.views.CarView)slinky.core.facade.ReactElement
[error]   called from org.tou.views.CarView.render
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   com.apollographql.scalajs.react.Query$
[error]   org.tou.views.CarView
[error] Referring to non-existent method magnolia.Magnolia$.caseClass(java.lang.String,scala.Boolean,scala.Boolean,[magnolia.Param,scala.Function1)magnolia.CaseClass
[error]   called from com.apollographql.scalajs.react.Query$.propsTypeclass$macro$56$1()slinky.readwrite.Writer
[error]   called from com.apollographql.scalajs.react.Query$.<init>()
[error]   called from org.tou.views.CarView.render(org.tou.views.CarView)slinky.core.facade.ReactElement
[error]   called from org.tou.views.CarView.render
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   com.apollographql.scalajs.react.Query$
[error]   org.tou.views.CarView

[error] org.scalajs.core.tools.linker.LinkingException: There were linking errors
[error]         at org.scalajs.core.tools.linker.frontend.BaseLinker.linkInternal(BaseLinker.scala:163)
[error]         at org.scalajs.core.tools.linker.frontend.BaseLinker.linkInternal(BaseLinker.scala:111)
[error]         at org.scalajs.core.tools.linker.frontend.LinkerFrontend.$anonfun$link$3(LinkerFrontend.scala:66)
[error]         at org.scalajs.core.tools.logging.Logger.time(Logger.scala:31)
[error]         at org.scalajs.core.tools.logging.Logger.time$(Logger.scala:29)
[error]         at org.scalajs.sbtplugin.Loggers$SbtLoggerWrapper.time(Loggers.scala:19)
[error]         at org.scalajs.core.tools.linker.frontend.LinkerFrontend.link(LinkerFrontend.scala:65)
[error]         at org.scalajs.core.tools.linker.Linker.$anonfun$link$1(Linker.scala:55)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at org.scalajs.core.tools.linker.Linker.guard(Linker.scala:72)
[error]         at org.scalajs.core.tools.linker.Linker.link(Linker.scala:53)
[error]         at org.scalajs.core.tools.linker.ClearableLinker.$anonfun$link$1(ClearableLinker.scala:55)
[error]         at org.scalajs.core.tools.linker.ClearableLinker.$anonfun$link$1$adapted(ClearableLinker.scala:55)
[error]         at org.scalajs.core.tools.linker.ClearableLinker.linkerOp(ClearableLinker.scala:66)
[error]         at org.scalajs.core.tools.linker.ClearableLinker.link(ClearableLinker.scala:55)
[error]         at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSStageSettings$11(ScalaJSPluginInternal.scala:327)
[error]         at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:73)
[error]         at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:147)
[error]         at sbt.util.Difference.apply(Tracked.scala:313)
[error]         at sbt.util.Difference.apply(Tracked.scala:293)
[error]         at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:143)
[error]         at sbt.util.Difference.apply(Tracked.scala:313)
[error]         at sbt.util.Difference.apply(Tracked.scala:288)
[error]         at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:142)
[error]         at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSStageSettings$10(ScalaJSPluginInternal.scala:332)
[error]         at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:44)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:64)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:266)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]         at java.lang.Thread.run(Thread.java:745)
[error] (cars/compile:fastOptJS) org.scalajs.core.tools.linker.LinkingException: There were linking errors

```

I have a very simple component query borrowed from your example:

```
package org.tou.views

import com.apollographql.scalajs.react.Query
import com.tou.Cars
import slinky.core.StatelessComponent
import slinky.core.annotations.react
import slinky.core.facade.ReactElement
import slinky.web.html.{div, h1}


@react class CarView extends StatelessComponent {
  type Props = Unit

  def render(): ReactElement = {
    Query(CarsQuery) {
      _.data.map { d =>
        div(
          d.queryResult.map(_.wheels.get).mkString(", ")
        )
      }.getOrElse(h1("loading!"))
    }
  }
}
```

my generated query looks like:
```
object CarsQuery extends com.apollographql.scalajs.GraphQLQuery {
  val operationString =
    "query Cars {" +
    "  queryResult: getCars{" +
    "    __typename" +
    "    carType" +
    "    wheels" +
    "    trim" +
    "  }" +
    "}"
  val operation = com.apollographql.scalajs.gql(operationString)

  type Variables = Unit

  case class Data(queryResult: Seq[Data.QueryResult]) {
  }

  object Data {
    val possibleTypes = scala.collection.Set("Query")

    case class QueryResult(carType: Option[String], wheels: Option[String], trim: Option[String]) {
    }

    object QueryResult {
      val possibleTypes = scala.collection.Set("CarGroups")
    }
  }
}
```

**Comment by evbo** [comment]
@shadaj figured it out: [there's a very important dependency](https://github.com/apollographql/apollo-scalajs/blob/master/core/build.sbt#L5) for the example's `core` dependency project.

Once I added that and updated all my other libraries to the latest and greatest it worked! Looking forward to your PR - closing this issue as now it's only a matter of you merging.

```
npmDependencies in Compile ++= Seq(
        "react" -> "16.7.0" ,
        "react-dom" -> "16.7.0",
        
        "react-apollo" -> "2.3.3",
        "apollo-boost" -> "0.1.23",
        "graphql" -> "14.0.2",
        "graphql-tag" -> "2.10.0"
      ),
      
      libraryDependencies ++= Seq(
        "me.shadaj" %%% "slinky-core" % "0.5.1",
        "me.shadaj" %%% "slinky-web" % "0.5.1",
        "me.shadaj" %%% "slinky-native" % "0.5.1", 
        "me.shadaj" %%% "slinky-hot" % "0.5.1",
        "me.shadaj" %%% "slinky-readwrite" % "0.5.1", // I was missing this one
        "com.apollographql" %%% "apollo-scalajs-react" % "0.4.3"
      )

```
